# Generated by Django 3.1.2 on 2021-03-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researcher',
            options={},
        ),
        migrations.AlterModelTable(
            name='researcher',
            table='researcher',
        ),
    ]
