# Generated by Django 3.1.2 on 2021-02-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customresearcher',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
