# Generated by Django 3.1.2 on 2021-03-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='researcher',
            table='researcher',
        ),
    ]
