# Generated by Django 3.1.1 on 2020-09-14 17:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
