# Generated by Django 3.1.2 on 2020-10-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0005_csvconverted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVConverted',
        ),
    ]
