# Generated by Django 3.1.2 on 2020-10-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0006_delete_csvconverted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('water', models.FloatField()),
                ('temp', models.FloatField()),
                ('pH', models.FloatField()),
                ('odo', models.FloatField()),
                ('salinity', models.FloatField()),
                ('turbid', models.FloatField()),
                ('bga', models.FloatField()),
                ('csv_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbqudasite.csvupload')),
            ],
        ),
    ]
