# Generated by Django 3.1.2 on 2020-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0008_auto_20201007_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='bga',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='odo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='pH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='salinity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='turbid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='water',
            field=models.FloatField(),
        ),
    ]
