# Generated by Django 3.1.2 on 2020-10-28 16:46

import bbqudasite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0009_auto_20201007_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(upload_to='csv/', validators=[bbqudasite.models.csv_file_validator]),
        ),
        migrations.AlterField(
            model_name='logupload',
            name='file',
            field=models.FileField(upload_to='log/', validators=[bbqudasite.models.log_file_validator]),
        ),
    ]
