# Generated by Django 3.1.2 on 2020-11-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0010_auto_20201028_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='custom_trails/')),
            ],
        ),
    ]
