# Generated by Django 3.1.2 on 2020-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0012_auto_20201103_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtrail',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='File Name'),
        ),
    ]
