# Generated by Django 3.1.2 on 2021-03-18 22:20

import bbqudasite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0013_customtrail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(upload_to='csv/<django.db.models.fields.related.ForeignKey>/', validators=[bbqudasite.models.csv_file_validator]),
        ),
    ]
