# Generated by Django 3.1.2 on 2021-04-06 01:15

import bbqudasite.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbqudasite', '0014_auto_20210318_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(upload_to='csv/', validators=[bbqudasite.models.csv_file_validator]),
        ),
        migrations.CreateModel(
            name='HeatmapCSVSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/', validators=[bbqudasite.models.csv_file_validator])),
                ('name', models.CharField(max_length=50, null=True, verbose_name='File Name')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('parameter', models.CharField(choices=[('Total Water Column (m)', 'Total Water Column (m)'), ('Temperature (c)', 'Temperature (c)'), ('pH', 'pH'), ('ODO mg/L', 'ODO mg/L'), ('Salinity (ppt)', 'Salinity (ppt)'), ('Turbid%2B NTU', 'Turbid+ NTU'), ('BGA-PC cells/mL', 'BGA-PC cells/mL')], max_length=22)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
