# Generated by Django 3.1.2 on 2021-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0015_auto_20210405_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtrail',
            name='file',
            field=models.FileField(upload_to='trail_generator/'),
        ),
    ]
